spring.application.name=reading-progress-service
server.port=8083

spring.data.mongodb.uri=mongodb://localhost:27017/readingdb

app.api.key=reading-service-secret-key

springdoc.swagger-ui.path=/swagger-ui.html
