spring.application.name=auth-service
server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/authdb

app.api.key=auth-service-secret-key
app.jwt.secret=BookNestSuperSecretKeyForJWTSigning1234567890
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
