spring.application.name=order-service
server.port=8084

spring.data.mongodb.uri=mongodb://localhost:27017/orderdb

app.api.key=order-service-secret-key

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

springdoc.swagger-ui.path=/swagger-ui.html
