spring.application.name=delivery-service
server.port=8085

spring.data.mongodb.uri=mongodb://localhost:27017/deliverydb

app.api.key=delivery-service-secret-key

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

springdoc.swagger-ui.path=/swagger-ui.html
